### PR TITLE
Pictures ggplot

### PR DESCRIPTION
**Pull request by yanlesin**
Hi Brian,
I added two functions to support attachment functionality per Pushover API (see issue #8) - pushover_attachment and ggpushover (inspired by Bob Rudis's implementation of the same function at SlackR package) to sent most recent ggplot as attachment to notification.

### CODE REVIEW

**Comment by briandconnelly** [comment]
@yanlesin thank you! This has been on my list for a VERY long time. I'm hoping to resume development on this package in the near future, so I plan to give this a solid read soon.

**Comment by michael-dewar** [comment]
I just want to say thanks to @briandconnelly and @yanlesin for your hard work on this package.  I've been using pushoverr for a while now and it is great.  And this new ggpushover function is really helpful.

**Comment by briandconnelly** [comment]
I've resumed development on this package and have made a lot of changes. My most recent push adds attachment support.

I really like the idea of `ggpushover()` and have no doubt sending plots would be one of the most frequent use cases, but I'm going to think a bit about the implementation. Including {ggplot2} is a huge dependency.

**Comment by yanlesin** [comment]
Understand... As soon as attachment functionality is implemented, it is possible to implement a wrapper that does ggpushover() relatively easy without having function inside Pushover package...

**Comment by michael-dewar** [comment]
Is it possible to add `ggplot` to Suggests, and then check if it's installed inside the `ggpushover()` function?  If `ggplot` is not installed, then only the function needs to error out.

**Comment by briandconnelly** [comment]
Yeah, I think publishing (via a vignette?) an example of how to easily send ggplot objects is definitely worth doing.

[Here's another PR](https://github.com/briandconnelly/pushoverr/pull/17) where I explored an alternate (and minimal) `ggpushoverr` function. It uses {rlang}'s `check_installed()` function to see if ggplot2 is installed, and works well.

The problem, though, is the WARNINGS that the build checks produce. The CRAN maintainers do not typically like seeing that. It's definitely possible to put it in the `Suggests`, but a lot of people by default install all suggested packages, which is a big ask. Though I realize the usefulness of it, I'm still not sure that the benefits outweigh all the costs, especially when a relatively straightforward wrapper function can be shared and written about.

**Comment by yanlesin** [comment]
Essentially I was saving temporary png file and attaching it to message... I would say - this will be a nice example, but I understand convenience too @michael-dewar

**Comment by michael-dewar** [comment]
Or you could simultaneously release a package called ggpushoverr that Requires both ggplot and pushoverr and contains the single wrapper function (and maybe re-exports all of pushoverr).

I wonder: if someone blindly installs all of the Suggests, then maybe they don't mind??

In any case, thanks for all of your work on the package.  It's really a lifesaver.

**Comment by yanlesin** [comment]
@michael-dewar do you need ggpushover package to be on CRAN? if not - this is really easy task.

**Comment by briandconnelly** [comment]
I'm preparing to submit the new version (1.1.0) to CRAN. Since it's so much different from this PR, I'm going to close this. I'm happy to revisit it in the future.

I've created [this gist](https://gist.github.com/briandconnelly/0435bf83a0abc7df59da0631d80504ed), which may be expanded to a vignette in the future, that demonstrates how a `ggpushover` function could be implemented using 1.1.0.

**Pull request closed without merging**
